/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#c24100",
        "surface-bright": "#373943",
        "on-secondary": "#480081",
        "on-background": "#e2e1ef",
        "surface-tint": "#b8c3ff",
        "on-primary-fixed-variant": "#0035be",
        "on-tertiary-fixed-variant": "#812800",
        "primary-fixed-dim": "#b8c3ff",
        "primary": "#b8c3ff",
        "inverse-primary": "#124af0",
        "on-tertiary-container": "#ffece6",
        "on-secondary-fixed-variant": "#6700b5",
        "primary-fixed": "#dde1ff",
        "tertiary-fixed-dim": "#ffb59b",
        "surface-container-highest": "#33343e",
        "surface-container-low": "#191b24",
        "secondary-fixed": "#efdbff",
        "secondary-fixed-dim": "#dcb8ff",
        "surface-container-high": "#282933",
        "on-primary-fixed": "#001356",
        "tertiary-fixed": "#ffdbcf",
        "secondary-container": "#7701d0",
        "surface-container": "#1d1f29",
        "outline-variant": "#434656",
        "on-tertiary": "#5b1a00",
        "on-surface": "#e2e1ef",
        "error": "#ffb4ab",
        "tertiary": "#ffb59b",
        "surface-container-lowest": "#0c0e17",
        "on-primary": "#002388",
        "secondary": "#dcb8ff",
        "on-secondary-container": "#dcb7ff",
        "surface-dim": "#11131c",
        "error-container": "#93000a",
        "surface-variant": "#33343e",
        "outline": "#8e90a2",
        "on-tertiary-fixed": "#380d00",
        "primary-container": "#2e5bff",
        "on-surface-variant": "#c4c5d9",
        "inverse-on-surface": "#2e303a",
        "background": "#11131c",
        "surface": "#11131c",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "inverse-surface": "#e2e1ef",
        "on-secondary-fixed": "#2c0051",
        "on-primary-container": "#efefff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "gutter": "12px",
        "container-padding": "20px"
      },
      fontFamily: {
        "body-base": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "data-mono": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-base": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "display-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "data-mono": ["18px", {"lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
